### ISSUE TITLE
Flashing effect at the end of a line makes it difficult to read.

### ISSUE THREAD

**Issue by MattSmiglarski** [ian-kelling/spray#3]
When spray-mode reaches the end of a line, there is an empty text gap in the updates. This causes a flashing effect which affects usability.

It seems to me that it would be easier to read during spray-mode if there is no flash at the end of the line. It is difficult to explain why, but it seems worth pointing out. FWIW, other algorithms avoid the flash.

**Comment by ian-kelling** [comment]
The change to the function below makes no flash. Do you think it would be worth having an option to turn it on and off? What exactly do you think is the best behavior? 

    (defun spray--update ()
      (cond ((not (zerop spray--initial-delay))
             (setq spray--initial-delay (1- spray--initial-delay)))
            ((not (zerop spray--delay))
             (setq spray--delay (1- spray--delay)))
            (t
             (widen)
             (if (eobp)
                 (spray-mode -1)
               (when (not (zerop spray--first-words))
                 (setq spray--initial-delay spray--first-words)
                 (setq spray--first-words (1- spray--first-words)))
               (skip-chars-forward "\s\t\n—")
               (spray--word-at-point)))))

**Comment by mpsmc** [comment]
It think that is a good change.

As I said, the reason why the flash affects the reading experience is difficult to explain, and I do see how it might be informative.

I would avoid having a configuration option unless there are examples of when it might be desirable.

**Comment by ian-kelling** [comment]
I applied this patch about a year ago but forgot to close the bug. I tend to hate any sort of flashing on my screen, so I agree it was better.
