### ISSUE TITLE
how to change the whole buffer background only in spray-mode?

### ISSUE THREAD

**Issue by stardiviner** [ian-kelling/spray#5]
![spray background](https://cloud.githubusercontent.com/assets/378699/7625835/a26cef14-fa2f-11e4-94d3-a0a833524bcb.png)

I got spray-mode enabled, and get upper effect.
I wish the whole background is white.

I tried the following way:
But it seems not work.
```lisp

;; TODO:
;; (add-hook 'spray-mode-hook
;;           (lambda ()
;;             (make-local-variable 'default
;;                                  (set-face-attribute 'default nil
;;                                                      :background "white"))))
(set-face-attribute 'spray-base-face nil
                    :inherit 'default
                    :foreground "black"
                    :background "white"
                    )
(set-face-attribute 'spray-accent-face nil
                    :inherit 'spray-base-face
                    :foreground "red"
                    )
```

**Comment by ian-kelling** [comment]
Good question. It might be a few weeks before I can dedicate time to look into this. If you figure it out, I can certainly add code to allow for it.

**Comment by stardiviner** [comment]
@ian-kelling I found a good solution, `color-theme-buffer-local`

- http://www.emacswiki.org/emacs/BufferBackgroundColor
- https://github.com/vic/color-theme-buffer-local

You can take a look on it.

**Comment by ian-kelling** [comment]
Thanks @stardiviner. If you have example code which uses some of this, feel free to post it. I've updated the readme to include what you found.
