### ISSUE TITLE
don't change the point position.

### ISSUE THREAD

**Issue by stardiviner** [ian-kelling/spray#8]
I think keep point at the original position is better.
I found the source code use `(skip-chars-forward "\s\t\n—")` to move forward.
So I think spray should backup current position, and restore after quit spray.
Maybe need to add a hook `spray-quit-hook`?

**Comment by ian-kelling** [comment]
Yes. I agree. pull requests are very welcome.

**Comment by ian-kelling** [comment]
I'm unconvinced this should be the default, so I added it as an option with  commit c52fc1.
